# Microfinance Fraud Detection using Machine Learning

## Data Understanding

### Objective

The goal of this notebook is to understand the structure, quality, and characteristics of the Microfinance Fraud Detection dataset before performing exploratory analysis and model development.

### Tasks

- Load the dataset
- Understand dataset dimensions
- Explore feature names
- Check data types
- Detect missing values
- Detect duplicate records
- Generate statistical summary
- Identify categorical and numerical features
- Analyze target variable distribution

In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
df = pd.read_csv("C:\\Users\\Dinesh\\OneDrive\\Desktop\\Microfinance-Fraud-Detection\\data\\raw\\microfinance_fraud_detection_dataset.csv")

print("dataset Loaded successfully")

dataset Loaded successfully

In [3]:
df.head()

,transaction_id,customer_id,branch_id,loan_id,customer_age,gender,marital_status,education_level,occupation,annual_income,monthly_expenses,credit_score,years_with_institution,previous_loan_count,dependents,home_ownership,mobile_registered,region,state,distance_to_branch_km,branch_transaction_volume,branch_fraud_rate_history,loan_purpose,requested_amount,approved_amount,disbursed_amount,loan_term_months,interest_rate,loan_to_income_ratio,collateral_provided,guarantors_count,group_lending,application_channel,processing_time_days,device_type,browser_type,network_type,scheduled_installment,actual_installment_paid,payment_frequency,days_overdue,missed_payments,total_payments_made,payment_method,remaining_balance,debt_service_ratio,payment_consistency,avg_monthly_transactions,avg_transaction_amount,total_transaction_volume,transaction_velocity,cash_out_percentage,suspicious_transaction_count,high_value_transaction_flag,unusual_transaction_ratio,app_login_frequency,app_login_anomaly_score,device_changes,ip_changes,sim_card_changes,account_age_days,failed_login_attempts,biometric_verification,blacklist_match,duplicate_application,identity_verification_failed,kyc_completeness,document_verification_score,sanctions_screening,pep_flag,aml_alert_count,reference_check_result,income_discrepancy,social_connections,fraudster_connections,same_address_users,network_risk_score,typing_speed_anomaly,click_pattern_anomaly,loan_status,days_since_disbursement,bureau_score,application_date,application_day_of_week,application_hour,income_stability_score,employment_tenure_years,credit_utilization_ratio,active_loans_count,total_debt_obligation,financial_dependency_ratio,savings_balance,penalty_charges,fraud_type,is_fraud
0,TXN000001,CUST01825,BR049,LOAN04822,43,Male,Divorced,Diploma,Retired,45591.89,36846.86,563,6.79,2,0,Rented,True,Remote Rural,Haryana,1.04,9455,0.0243,Small Business,26559.11,19613.18,16202.64,6,23.95,5.1623,True,1,False,Branch Visit,18.16,Agent/Branch Device,Not Applicable,Branch Network,4051.76,528.08,Irregular,1,3,7,Bank Transfer,4960.41,1.0664,0.8096,5,4443.11,266586.60,20.60,56.94,1,False,0.2167,13,0.5011,1,1,0,711,4,False,False,False,False,16.12,94.30,Clear,False,2,Verified,False,17,0,1,0.1240,0.6098,0.2156,Closed,585,422,2024-05-21,Tuesday,18,0.7108,25.09,0.3091,1,70864.38,1.5543,366.27,2.69,Not Fraud,0
1,TXN000002,CUST00410,BR174,LOAN05235,36,Male,Married,Primary,Farmer,75316.77,50231.18,663,0.36,6,2,Owned,True,Semi-Urban,West Bengal,9.04,1732,0.0441,Education,26857.44,21387.95,20423.68,6,18.01,3.4077,False,1,False,Mobile App,22.97,Android Phone,Firefox,4G,4206.65,6173.26,Weekly,0,1,1,Mobile Money,17144.45,0.6702,0.3402,10,2147.33,257679.60,11.51,89.48,3,False,0.3330,6,0.6328,1,6,0,120,2,False,False,False,False,86.91,15.57,Clear,False,0,Failed,False,12,0,1,0.6543,0.1977,0.3749,Restructured,472,534,2024-08-27,Tuesday,16,0.5664,2.49,0.0835,2,76609.22,1.0172,3837.05,0.00,Not Fraud,0
2,TXN000003,CUST04507,BR163,LOAN07508,45,Female,Married,PhD,Small Business Owner,53905.76,48578.39,544,2.34,0,2,Owned,True,Remote Rural,Kerala,1.92,769,0.0361,Health,10889.98,8453.29,7818.83,12,16.22,1.8818,False,0,True,Online Portal,41.61,Tablet,Edge,WiFi,818.70,504.80,Bi-Weekly,0,0,33,Mobile Money,0.00,0.1823,0.7564,14,9784.07,1643723.76,48.22,81.03,3,True,0.4542,17,0.3165,3,3,0,1843,2,True,False,False,False,85.40,36.21,Clear,False,0,Verified,False,19,0,2,0.7674,0.0450,0.7717,Closed,57,554,2023-10-12,Thursday,18,0.7840,2.72,0.6358,1,97220.41,1.8035,698.63,0.00,Not Fraud,0
3,TXN000004,CUST04013,BR158,LOAN12869,56,Female,Single,Secondary,Self-Employed,34222.08,28662.02,637,4.09,2,0,Owned,True,Urban,Uttar Pradesh,15.27,2690,0.0210,Small Business,4880.98,3466.50,3247.24,24,17.53,1.2155,False,0,False,Branch Visit,17.44,Agent/Branch Device,Not Applicable,Branch Network,169.76,44.98,Weekly,0,2,17,Bank Transfer,925.01,0.0595,0.1070,7,4609.24,387176.16,44.78,63.74,1,False,0.0133,18,0.4802,1,3,0,1856,2,False,False,False,False,65.61,26.28,Clear,False,1,Not Done,False,15,0,1,0.9841,0.7134,0.9882,Active,514,582,2023-04-14,Friday,9,0.6262,12.82,0.2256,4,36526.56,1.0673,2177.94,0.00,Not Fraud,0
4,TXN000005,CUST03658,BR021,LOAN06457,35,Male,Divorced,Secondary,Salaried Employee,89250.89,52902.34,613,9.07,4,1,Rented,True,Urban,Maharashtra,3.92,236,0.0536,Housing,11591.01,9103.24,8001.48,12,10.89,1.2240,False,0,True,Agent/Field Officer,34.70,Agent/Branch Device,Not Applicable,Branch Network,841.22,1014.56,Monthly,0,1,3,Bank Transfer,6497.81,0.1131,0.9144,12,1719.41,247595.04,5.78,4.47,0,False,0.3282,12,0.3700,1,3,0,611,0,False,False,False,False,23.46,70.25,Clear,False,0,Partial,False,12,0,0,0.8713,0.0567,0.6876,Defaulted,114,652,2024-03-30,Saturday,18,0.8419,14.37,1.0249,2,150323.27,1.6843,13883.37,0.00,Not Fraud,0

In [4]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 50000
Columns : 95

In [5]:
df.columns.tolist()

['transaction_id',
 'customer_id',
 'branch_id',
 'loan_id',
 'customer_age',
 'gender',
 'marital_status',
 'education_level',
 'occupation',
 'annual_income',
 'monthly_expenses',
 'credit_score',
 'years_with_institution',
 'previous_loan_count',
 'dependents',
 'home_ownership',
 'mobile_registered',
 'region',
 'state',
 'distance_to_branch_km',
 'branch_transaction_volume',
 'branch_fraud_rate_history',
 'loan_purpose',
 'requested_amount',
 'approved_amount',
 'disbursed_amount',
 'loan_term_months',
 'interest_rate',
 'loan_to_income_ratio',
 'collateral_provided',
 'guarantors_count',
 'group_lending',
 'application_channel',
 'processing_time_days',
 'device_type',
 'browser_type',
 'network_type',
 'scheduled_installment',
 'actual_installment_paid',
 'payment_frequency',
 'days_overdue',
 'missed_payments',
 'total_payments_made',
 'payment_method',
 'remaining_balance',
 'debt_service_ratio',
 'payment_consistency',
 'avg_monthly_transactions',
 'avg_transaction_amount',
 'total_transaction_volume',
 'transaction_velocity',
 'cash_out_percentage',
 'suspicious_transaction_count',
 'high_value_transaction_flag',
 'unusual_transaction_ratio',
 'app_login_frequency',
 'app_login_anomaly_score',
 'device_changes',
 'ip_changes',
 'sim_card_changes',
 'account_age_days',
 'failed_login_attempts',
 'biometric_verification',
 'blacklist_match',
 'duplicate_application',
 'identity_verification_failed',
 'kyc_completeness',
 'document_verification_score',
 'sanctions_screening',
 'pep_flag',
 'aml_alert_count',
 'reference_check_result',
 'income_discrepancy',
 'social_connections',
 'fraudster_connections',
 'same_address_users',
 'network_risk_score',
 'typing_speed_anomaly',
 'click_pattern_anomaly',
 'loan_status',
 'days_since_disbursement',
 'bureau_score',
 'application_date',
 'application_day_of_week',
 'application_hour',
 'income_stability_score',
 'employment_tenure_years',
 'credit_utilization_ratio',
 'active_loans_count',
 'total_debt_obligation',
 'financial_dependency_ratio',
 'savings_balance',
 'penalty_charges',
 'fraud_type',
 'is_fraud']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 95 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   transaction_id                50000 non-null  str
 1   customer_id                   50000 non-null  str
 2   branch_id                     50000 non-null  str
 3   loan_id                       50000 non-null  str
 4   customer_age                  50000 non-null  int64
 5   gender                        50000 non-null  str
 6   marital_status                50000 non-null  str
 7   education_level               50000 non-null  str
 8   occupation                    50000 non-null  str
 9   annual_income                 50000 non-null  float64
 10  monthly_expenses              50000 non-null  float64
 11  credit_score                  50000 non-null  int64
 12  years_with_institution        50000 non-null  float64
 13  previous_loan_count           50000 non-null  int64
 14  dependents                    50000 non-null  int64
 15  home_ownership                50000 non-null  str
 16  mobile_registered             50000 non-null  bool
 17  region                        50000 non-null  str
 18  state                         50000 non-null  str
 19  distance_to_branch_km         50000 non-null  float64
 20  branch_transaction_volume     50000 non-null  int64
 21  branch_fraud_rate_history     50000 non-null  float64
 22  loan_purpose                  50000 non-null  str
 23  requested_amount              50000 non-null  float64
 24  approved_amount               50000 non-null  float64
 25  disbursed_amount              50000 non-null  float64
 26  loan_term_months              50000 non-null  int64
 27  interest_rate                 50000 non-null  float64
 28  loan_to_income_ratio          50000 non-null  float64
 29  collateral_provided           50000 non-null  bool
 30  guarantors_count              50000 non-null  int64
 31  group_lending                 50000 non-null  bool
 32  application_channel           50000 non-null  str
 33  processing_time_days          50000 non-null  float64
 34  device_type                   50000 non-null  str
 35  browser_type                  50000 non-null  str
 36  network_type                  50000 non-null  str
 37  scheduled_installment         50000 non-null  float64
 38  actual_installment_paid       50000 non-null  float64
 39  payment_frequency             50000 non-null  str
 40  days_overdue                  50000 non-null  int64
 41  missed_payments               50000 non-null  int64
 42  total_payments_made           50000 non-null  int64
 43  payment_method                50000 non-null  str
 44  remaining_balance             50000 non-null  float64
 45  debt_service_ratio            50000 non-null  float64
 46  payment_consistency           50000 non-null  float64
 47  avg_monthly_transactions      50000 non-null  int64
 48  avg_transaction_amount        50000 non-null  float64
 49  total_transaction_volume      50000 non-null  float64
 50  transaction_velocity          50000 non-null  float64
 51  cash_out_percentage           50000 non-null  float64
 52  suspicious_transaction_count  50000 non-null  int64
 53  high_value_transaction_flag   50000 non-null  bool
 54  unusual_transaction_ratio     50000 non-null  float64
 55  app_login_frequency           50000 non-null  int64
 56  app_login_anomaly_score       50000 non-null  float64
 57  device_changes                50000 non-null  int64
 58  ip_changes                    50000 non-null  int64
 59  sim_card_changes              50000 non-null  int64
 60  account_age_days              50000 non-null  int64
 61  failed_login_attempts         50000 non-null  int64
 62  biometric_verification        50000 non-null  bool
 63  blacklist_match               50000 non-null  bool
 64  duplicate_application         50000 non-null  bool
 65  identity_verification_failed  50000 non-null  bool
 66  kyc_completeness              50000 non-null  float64
 67  document_verification_score   50000 non-null  float64
 68  sanctions_screening           50000 non-null  str
 69  pep_flag                      50000 non-null  bool
 70  aml_alert_count               50000 non-null  int64
 71  reference_check_result        50000 non-null  str
 72  income_discrepancy            50000 non-null  bool
 73  social_connections            50000 non-null  int64
 74  fraudster_connections         50000 non-null  int64
 75  same_address_users            50000 non-null  int64
 76  network_risk_score            50000 non-null  float64
 77  typing_speed_anomaly          50000 non-null  float64
 78  click_pattern_anomaly         50000 non-null  float64
 79  loan_status                   50000 non-null  str
 80  days_since_disbursement       50000 non-null  int64
 81  bureau_score                  50000 non-null  int64
 82  application_date              50000 non-null  str
 83  application_day_of_week       50000 non-null  str
 84  application_hour              50000 non-null  int64
 85  income_stability_score        50000 non-null  float64
 86  employment_tenure_years       50000 non-null  float64
 87  credit_utilization_ratio      50000 non-null  float64
 88  active_loans_count            50000 non-null  int64
 89  total_debt_obligation         50000 non-null  float64
 90  financial_dependency_ratio    50000 non-null  float64
 91  savings_balance               50000 non-null  float64
 92  penalty_charges               50000 non-null  float64
 93  fraud_type                    50000 non-null  str
 94  is_fraud                      50000 non-null  int64
dtypes: bool(10), float64(34), int64(27), str(24)
memory usage: 32.9 MB

In [7]:
missing = df.isnull().sum()

missing = missing[missing > 0]

In [8]:
duplicates = df.duplicated().sum()

print("Duplicate Rows : ", duplicates)

Duplicate Rows :  0

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_age,50000.0,37.762780,11.452916,18.0000,29.000000,38.00000,46.000000,8.000000e+01
annual_income,50000.0,49268.755009,42573.657077,1200.0000,21153.495000,36279.00500,62178.000000,2.500000e+05
monthly_expenses,50000.0,33249.962626,30432.378850,608.6600,13486.252500,23773.21500,41916.375000,2.361509e+05
credit_score,50000.0,643.511100,86.180634,300.0000,586.000000,644.00000,702.000000,8.500000e+02
years_with_institution,50000.0,3.014100,2.992990,0.1000,0.870000,2.11000,4.160000,2.500000e+01
previous_loan_count,50000.0,1.998540,1.405026,0.0000,1.000000,2.00000,3.000000,1.100000e+01
dependents,50000.0,2.259260,1.608047,0.0000,1.000000,2.00000,3.000000,6.000000e+00
distance_to_branch_km,50000.0,4.993392,4.996572,0.1000,1.430000,3.45000,6.900000,4.905000e+01
branch_transaction_volume,50000.0,5047.483080,2855.500823,100.0000,2562.000000,5053.00000,7513.000000,9.999000e+03
branch_fraud_rate_history,50000.0,0.032508,0.015932,0.0050,0.018700,0.03250,0.046400,6.000000e-02
requested_amount,50000.0,15229.835364,17640.411654,500.0000,4430.030000,9023.91000,18695.457500,1.000000e+05
approved_amount,50000.0,11402.724779,13587.547740,255.8600,3206.250000,6664.07500,13914.082500,9.995888e+04
disbursed_amount,50000.0,10263.760162,12280.948666,212.0900,2880.070000,5977.86500,12513.787500,9.846771e+04
loan_term_months,50000.0,16.204500,9.487316,3.0000,6.000000,18.00000,24.000000,3.600000e+01
interest_rate,50000.0,18.227541,5.647552,8.0000,14.160000,18.12000,22.070000,3.500000e+01
loan_to_income_ratio,50000.0,2.842576,2.277724,0.1097,1.350200,2.20910,3.606350,4.064720e+01
guarantors_count,50000.0,1.042080,0.969932,0.0000,0.000000,1.00000,2.000000,3.000000e+00
processing_time_days,50000.0,30.450834,17.055899,1.0000,15.770000,30.27000,45.360000,6.000000e+01
scheduled_installment,50000.0,1376.142582,2481.265937,8.4900,246.485000,581.91000,1436.827500,3.946191e+04
actual_installment_paid,50000.0,1036.932910,2235.015308,0.0100,123.067500,355.83500,1001.507500,5.130196e+04
days_overdue,50000.0,5.068180,11.230945,0.0000,0.000000,0.00000,5.000000,1.480000e+02
missed_payments,50000.0,1.997520,1.421532,0.0000,1.000000,2.00000,3.000000,1.100000e+01
total_payments_made,50000.0,17.983440,10.112694,1.0000,9.000000,18.00000,27.000000,3.500000e+01
remaining_balance,50000.0,2620.139282,6337.225606,0.0000,0.000000,0.00000,2403.117500,9.203706e+04
debt_service_ratio,50000.0,0.342909,0.469102,0.0050,0.097200,0.18750,0.390500,1.154070e+01
payment_consistency,50000.0,0.499762,0.287875,0.0000,0.252400,0.49840,0.750625,1.000000e+00
avg_monthly_transactions,50000.0,7.996340,2.831340,0.0000,6.000000,8.00000,10.000000,2.500000e+01
avg_transaction_amount,50000.0,6750.716790,6414.338819,184.1400,2873.597500,4893.14500,8381.025000,1.412732e+05
total_transaction_volume,50000.0,647712.828209,694707.744165,0.0000,242545.500000,442450.02000,801037.230000,2.203862e+07
transaction_velocity,50000.0,25.150091,14.396121,0.1000,12.777500,25.24000,37.630000,5.000000e+01
cash_out_percentage,50000.0,49.897411,28.875955,0.0000,24.730000,50.08000,74.872500,1.000000e+02
suspicious_transaction_count,50000.0,1.000540,1.001619,0.0000,0.000000,1.00000,2.000000,8.000000e+00
unusual_transaction_ratio,50000.0,0.249087,0.144171,0.0000,0.124300,0.24820,0.374300,5.000000e-01
app_login_frequency,50000.0,15.000480,3.860344,2.0000,12.000000,15.00000,18.000000,3.400000e+01
app_login_anomaly_score,50000.0,0.499287,0.289922,0.0000,0.246900,0.49780,0.750300,1.000000e+00
device_changes,50000.0,1.004020,1.002768,0.0000,0.000000,1.00000,2.000000,7.000000e+00
ip_changes,50000.0,2.991140,1.722289,0.0000,2.000000,3.00000,4.000000,1.200000e+01
sim_card_changes,50000.0,0.495520,0.861229,0.0000,0.000000,0.00000,1.000000,3.000000e+00
account_age_days,50000.0,1015.338440,569.128488,30.0000,520.000000,1014.50000,1510.000000,1.999000e+03
failed_login_attempts,50000.0,2.009580,1.419355,0.0000,1.000000,2.00000,3.000000,1.200000e+01
kyc_completeness,50000.0,49.886495,28.959527,0.0000,24.800000,49.82000,74.942500,1.000000e+02
document_verification_score,50000.0,49.751733,28.825804,0.0000,24.770000,49.67000,74.670000,1.000000e+02
aml_alert_count,50000.0,0.594980,0.774126,0.0000,0.000000,0.00000,1.000000,6.000000e+00
social_connections,50000.0,15.013620,3.865873,2.0000,12.000000,15.00000,18.000000,3.400000e+01
fraudster_connections,50000.0,0.399300,0.632951,0.0000,0.000000,0.00000,1.000000,6.000000e+00
same_address_users,50000.0,1.002620,0.999016,0.0000,0.000000,1.00000,2.000000,7.000000e+00
network_risk_score,50000.0,0.500554,0.288532,0.0000,0.250900,0.49940,0.751500,1.000000e+00
typing_speed_anomaly,50000.0,0.499441,0.289317,0.0000,0.248600,0.49930,0.750525,1.000000e+00
click_pattern_anomaly,50000.0,0.499874,0.287534,0.0000,0.251900,0.50050,0.747425,1.000000e+00
days_since_disbursement,50000.0,367.049640,210.292139,1.0000,186.000000,367.00000,550.000000,7.290000e+02
bureau_score,50000.0,536.412500,103.784696,119.0000,466.000000,537.00000,607.000000,9.000000e+02
application_hour,50000.0,13.537080,4.608502,6.0000,10.000000,14.00000,18.000000,2.100000e+01
income_stability_score,50000.0,0.550515,0.259890,0.1000,0.324400,0.55180,0.776600,1.000000e+00
employment_tenure_years,50000.0,7.722459,6.471960,0.1000,3.237500,5.89000,10.140000,4.000000e+01
credit_utilization_ratio,50000.0,0.753102,0.433569,0.0000,0.375750,0.75550,1.128400,1.500000e+00
active_loans_count,50000.0,2.007440,1.419037,0.0000,1.000000,2.00000,3.000000,1.000000e+01
total_debt_obligation,50000.0,68080.237663,36372.972337,6889.8300,42792.695000,59984.25000,84068.547500,4.898541e+05
financial_dependency_ratio,50000.0,2.587354,3.050682,0.0396,0.869375,1.65705,3.140875,6.145880e+01
savings_balance,50000.0,3393.349311,9747.793835,1.8700,398.775000,1096.29000,3027.900000,6.482554e+05
penalty_charges,50000.0,13.971834,34.938279,0.0000,0.000000,0.00000,9.582500,6.848400e+02
is_fraud,50000.0,0.030260,0.171304,0.0000,0.000000,0.00000,0.000000,1.000000e+00

In [12]:
categorical_columns = df.select_dtypes(include=["object"]).columns.tolist()

print("Categorical Features")

categorical_columns

Categorical Features

C:\Users\Dinesh\AppData\Local\Temp\ipykernel_14144\3934334861.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns.tolist()

['transaction_id',
 'customer_id',
 'branch_id',
 'loan_id',
 'gender',
 'marital_status',
 'education_level',
 'occupation',
 'home_ownership',
 'region',
 'state',
 'loan_purpose',
 'application_channel',
 'device_type',
 'browser_type',
 'network_type',
 'payment_frequency',
 'payment_method',
 'sanctions_screening',
 'reference_check_result',
 'loan_status',
 'application_date',
 'application_day_of_week',
 'fraud_type']

In [13]:
boolean_columns = df.select_dtypes(include=["bool"]).columns.tolist()
print("Boolean Features")
boolean_columns

Boolean Features

['mobile_registered',
 'collateral_provided',
 'group_lending',
 'high_value_transaction_flag',
 'biometric_verification',
 'blacklist_match',
 'duplicate_application',
 'identity_verification_failed',
 'pep_flag',
 'income_discrepancy']

In [14]:
df["is_fraud"].value_counts()

is_fraud
0    48487
1     1513
Name: count, dtype: int64

In [15]:
(df["is_fraud"].value_counts(normalize=True) * 100).round(2)

is_fraud
0    96.97
1     3.03
Name: proportion, dtype: float64

In [16]:
df.nunique().sort_values()

group_lending                       2
collateral_provided                 2
mobile_registered                   2
biometric_verification              2
blacklist_match                     2
high_value_transaction_flag         2
identity_verification_failed        2
duplicate_application               2
income_discrepancy                  2
pep_flag                            2
is_fraud                            2
sanctions_screening                 3
gender                              3
marital_status                      4
payment_frequency                   4
region                              4
guarantors_count                    4
reference_check_result              4
home_ownership                      4
sim_card_changes                    4
loan_status                         5
application_channel                 5
payment_method                      5
loan_term_months                    6
device_type                         6
education_level                     7
dependents                          7
network_type                        7
browser_type                        7
application_day_of_week             7
aml_alert_count                     7
fraudster_connections               7
same_address_users                  8
device_changes                      8
occupation                          8
fraud_type                          8
loan_purpose                        8
suspicious_transaction_count        9
active_loans_count                 11
previous_loan_count                12
failed_login_attempts              12
missed_payments                    12
ip_changes                         13
application_hour                   16
state                              20
avg_monthly_transactions           24
social_connections                 33
app_login_frequency                33
total_payments_made                35
customer_age                       63
days_overdue                      115
branch_id                         200
credit_score                      511
branch_fraud_rate_history         551
bureau_score                      689
days_since_disbursement           729
application_date                  731
years_with_institution           1691
account_age_days                 1970
interest_rate                    2588
distance_to_branch_km            2602
employment_tenure_years          3203
transaction_velocity             4991
unusual_transaction_ratio        5001
processing_time_days             5901
penalty_charges                  7984
income_stability_score           8972
branch_transaction_volume        9853
app_login_anomaly_score          9919
network_risk_score               9922
typing_speed_anomaly             9926
payment_consistency              9932
document_verification_score      9932
kyc_completeness                 9935
click_pattern_anomaly            9936
customer_id                      9937
cash_out_percentage              9940
debt_service_ratio              11117
loan_id                         14449
credit_utilization_ratio        14474
remaining_balance               22622
financial_dependency_ratio      31675
loan_to_income_ratio            32627
actual_installment_paid         40816
scheduled_installment           43807
savings_balance                 46539
requested_amount                48854
avg_transaction_amount          48912
disbursed_amount                49317
approved_amount                 49377
annual_income                   49468
total_transaction_volume        49675
monthly_expenses                49787
total_debt_obligation           49862
transaction_id                  50000
dtype: int64

# Initial Observations

### Dataset Summary

- Dataset contains customer, loan, transaction, digital behavior, and compliance information.
- Target variable is **is_fraud**.
- Fraud cases are expected to represent a small percentage of the dataset.
- Dataset contains numerical, categorical, and boolean features.
- No preprocessing has been applied yet.
- Data understanding is completed successfully.